/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Script;

import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class ADM_Daftar_Customer extends javax.swing.JPanel {
    public ResultSet rs = null;
    private final ADM_Kelola_Pelanggan kelola = new ADM_Kelola_Pelanggan();
 ;
    private String sql;

    
    public ADM_Daftar_Customer() {
        initComponents();              
    }

//  Metode Menampilkan Data Ke Tabel
    public void loadData(){
        DefaultTableModel model = (DefaultTableModel) tableContainer.getModel();
        model.setRowCount(0);

        //Query SQL Untuk Mengambil Data        
        sql = "SELECT * FROM pelanggan";                  
        
        try (PreparedStatement ps = AP_Database.con.prepareStatement(sql))
        {
            rs = ps.executeQuery();

            // Blok Menambahkan Value Ke Tabel 
            while (rs.next()) 
            {
                model.addRow(new Object[]{
                    rs.getString("id_user"),
                    rs.getString("nama"),
                    rs.getString("telepon"),
                    rs.getString("alamat")                   
                });
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
//  Metode Pencarian Data
    public void cariData(String key){
        DefaultTableModel model = (DefaultTableModel) tableContainer.getModel();
        model.setRowCount(0);

        //Query SQL Untuk Pencarian Data        
        sql = "SELECT * FROM pelanggan WHERE id_user LIKE ? OR nama LIKE ? OR telepon LIKE ? OR alamat LIKE ?";

        try(PreparedStatement ps = AP_Database.con.prepareStatement(sql))
        {
            //ASsign Value Pencarian Ke Sql
            String cari_value = "%" + key + "%";
            ps.setString(1, cari_value);
            ps.setString(2, cari_value);
            ps.setString(3, cari_value);
            ps.setString(4, cari_value);            
            rs = ps.executeQuery();
            
            // Blok Menambahkan Value Ke Tabel 
            while (rs.next()) 
            {
                model.addRow(new Object[]{
                    rs.getString("id_user"),
                    rs.getString("nama"),
                    rs.getString("telepon"),
                    rs.getString("alamat") 
                });
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void kelolaData(){
        int row = tableContainer.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih pesanan dulu");
            return;
        }

        String id_pelanggan = tableContainer.getValueAt(row, 0).toString();
        
        kelola.loadData(id_pelanggan);
        kelola.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableContainer = new javax.swing.JTable();
        cari = new javax.swing.JButton();
        kelola_data = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tableContainer.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        tableContainer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Customer", "Nama Customer", "No Telepon", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableContainer.setRowHeight(30);
        tableContainer.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableContainer);
        if (tableContainer.getColumnModel().getColumnCount() > 0) {
            tableContainer.getColumnModel().getColumn(0).setResizable(false);
            tableContainer.getColumnModel().getColumn(1).setResizable(false);
            tableContainer.getColumnModel().getColumn(2).setResizable(false);
            tableContainer.getColumnModel().getColumn(3).setResizable(false);
        }

        cari.setBackground(new java.awt.Color(40, 90, 200));
        cari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cari.setForeground(new java.awt.Color(255, 255, 255));
        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        kelola_data.setBackground(new java.awt.Color(40, 90, 200));
        kelola_data.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kelola_data.setForeground(new java.awt.Color(255, 255, 255));
        kelola_data.setText("Kelola Data");
        kelola_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelola_dataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kelola_data)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kelola_data, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

//  Fitur Pencarian
    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        String cari_value = JOptionPane.showInputDialog(this, "Cari Data:");

        if (cari_value != null && !cari_value.trim().isEmpty()) {
            cariData(cari_value);
        } 
    }//GEN-LAST:event_cariActionPerformed

    private void kelola_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelola_dataActionPerformed
        // TODO add your handling code here:
        kelolaData();
    }//GEN-LAST:event_kelola_dataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kelola_data;
    private javax.swing.JTable tableContainer;
    // End of variables declaration//GEN-END:variables
}
